// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

@SuppressWarnings("unused")
public final class CustomData extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static CustomData getRootAsCustomData(ByteBuffer _bb) {
        return getRootAsCustomData(_bb, new CustomData());
    }

    public static CustomData getRootAsCustomData(ByteBuffer _bb, CustomData obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public CustomData __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public long typeId() {
        int o = __offset(4);
        return o != 0 ? (long) bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L;
    }

    public int payload(int j) {
        int o = __offset(6);
        return o != 0 ? bb.get(__vector(o) + j) & 0xFF : 0;
    }

    public int payloadLength() {
        int o = __offset(6);
        return o != 0 ? __vector_len(o) : 0;
    }

    public ByteVector payloadVector() {
        return payloadVector(new ByteVector());
    }

    public ByteVector payloadVector(ByteVector obj) {
        int o = __offset(6);
        return o != 0 ? obj.__assign(__vector(o), bb) : null;
    }

    public ByteBuffer payloadAsByteBuffer() {
        return __vector_as_bytebuffer(6, 1);
    }

    public ByteBuffer payloadInByteBuffer(ByteBuffer _bb) {
        return __vector_in_bytebuffer(_bb, 6, 1);
    }

    public static int createCustomData(FlatBufferBuilder builder, long typeId, int payloadOffset) {
        builder.startTable(2);
        CustomData.addPayload(builder, payloadOffset);
        CustomData.addTypeId(builder, typeId);
        return CustomData.endCustomData(builder);
    }

    public static void startCustomData(FlatBufferBuilder builder) {
        builder.startTable(2);
    }

    public static void addTypeId(FlatBufferBuilder builder, long typeId) {
        builder.addInt(0, (int) typeId, (int) 0L);
    }

    public static void addPayload(FlatBufferBuilder builder, int payloadOffset) {
        builder.addOffset(1, payloadOffset, 0);
    }

    public static int createPayloadVector(FlatBufferBuilder builder, byte[] data) {
        return builder.createByteVector(data);
    }

    public static int createPayloadVector(FlatBufferBuilder builder, ByteBuffer data) {
        return builder.createByteVector(data);
    }

    public static void startPayloadVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(1, numElems, 1);
    }

    public static int endCustomData(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public CustomData get(int j) {
            return get(new CustomData(), j);
        }

        public CustomData get(CustomData obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
