// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

/**
 * A decoration rectangle in absolute document coordinates (top-left origin),
 * derived from a span's glyph extents: kind 0 = background (highlight /
 * inline-code), 1 = underline, 2 = strikethrough.
 */
@SuppressWarnings("unused")
public final class DecorationRect extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static DecorationRect getRootAsDecorationRect(ByteBuffer _bb) {
        return getRootAsDecorationRect(_bb, new DecorationRect());
    }

    public static DecorationRect getRootAsDecorationRect(ByteBuffer _bb, DecorationRect obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public DecorationRect __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public long node() {
        int o = __offset(4);
        return o != 0 ? (long) bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L;
    }

    public float x() {
        int o = __offset(6);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float y() {
        int o = __offset(8);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float w() {
        int o = __offset(10);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float h() {
        int o = __offset(12);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public long argb() {
        int o = __offset(14);
        return o != 0 ? (long) bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L;
    }

    public byte kind() {
        int o = __offset(16);
        return o != 0 ? bb.get(o + bb_pos) : 0;
    }

    public static int createDecorationRect(FlatBufferBuilder builder, long node, float x, float y, float w, float h,
        long argb, byte kind) {
        builder.startTable(7);
        DecorationRect.addArgb(builder, argb);
        DecorationRect.addH(builder, h);
        DecorationRect.addW(builder, w);
        DecorationRect.addY(builder, y);
        DecorationRect.addX(builder, x);
        DecorationRect.addNode(builder, node);
        DecorationRect.addKind(builder, kind);
        return DecorationRect.endDecorationRect(builder);
    }

    public static void startDecorationRect(FlatBufferBuilder builder) {
        builder.startTable(7);
    }

    public static void addNode(FlatBufferBuilder builder, long node) {
        builder.addInt(0, (int) node, (int) 0L);
    }

    public static void addX(FlatBufferBuilder builder, float x) {
        builder.addFloat(1, x, 0.0f);
    }

    public static void addY(FlatBufferBuilder builder, float y) {
        builder.addFloat(2, y, 0.0f);
    }

    public static void addW(FlatBufferBuilder builder, float w) {
        builder.addFloat(3, w, 0.0f);
    }

    public static void addH(FlatBufferBuilder builder, float h) {
        builder.addFloat(4, h, 0.0f);
    }

    public static void addArgb(FlatBufferBuilder builder, long argb) {
        builder.addInt(5, (int) argb, (int) 0L);
    }

    public static void addKind(FlatBufferBuilder builder, byte kind) {
        builder.addByte(6, kind, 0);
    }

    public static int endDecorationRect(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public DecorationRect get(int j) {
            return get(new DecorationRect(), j);
        }

        public DecorationRect get(DecorationRect obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
