// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

@SuppressWarnings("unused")
public final class FlatLayout extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static FlatLayout getRootAsFlatLayout(ByteBuffer _bb) {
        return getRootAsFlatLayout(_bb, new FlatLayout());
    }

    public static FlatLayout getRootAsFlatLayout(ByteBuffer _bb, FlatLayout obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public FlatLayout __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public float x() {
        int o = __offset(4);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float y() {
        int o = __offset(6);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float w() {
        int o = __offset(8);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float h() {
        int o = __offset(10);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public long order() {
        int o = __offset(12);
        return o != 0 ? (long) bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L;
    }

    public static int createFlatLayout(FlatBufferBuilder builder, float x, float y, float w, float h, long order) {
        builder.startTable(5);
        FlatLayout.addOrder(builder, order);
        FlatLayout.addH(builder, h);
        FlatLayout.addW(builder, w);
        FlatLayout.addY(builder, y);
        FlatLayout.addX(builder, x);
        return FlatLayout.endFlatLayout(builder);
    }

    public static void startFlatLayout(FlatBufferBuilder builder) {
        builder.startTable(5);
    }

    public static void addX(FlatBufferBuilder builder, float x) {
        builder.addFloat(0, x, 0.0f);
    }

    public static void addY(FlatBufferBuilder builder, float y) {
        builder.addFloat(1, y, 0.0f);
    }

    public static void addW(FlatBufferBuilder builder, float w) {
        builder.addFloat(2, w, 0.0f);
    }

    public static void addH(FlatBufferBuilder builder, float h) {
        builder.addFloat(3, h, 0.0f);
    }

    public static void addOrder(FlatBufferBuilder builder, long order) {
        builder.addInt(4, (int) order, (int) 0L);
    }

    public static int endFlatLayout(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public FlatLayout get(int j) {
            return get(new FlatLayout(), j);
        }

        public FlatLayout get(FlatLayout obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
