// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

/**
 * One forbidden interval the text must not occupy, in paragraph-relative
 * coordinates (typically a float's rect ∩ the paragraph). The Rust line
 * breaker subtracts clips from the available width per line: x<=0 is a
 * left-side clip (text starts right of x+width), otherwise a right-side
 * clip (text ends at x).
 */
@SuppressWarnings("unused")
public final class FloatClip extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static FloatClip getRootAsFloatClip(ByteBuffer _bb) {
        return getRootAsFloatClip(_bb, new FloatClip());
    }

    public static FloatClip getRootAsFloatClip(ByteBuffer _bb, FloatClip obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public FloatClip __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public float yTop() {
        int o = __offset(4);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float yBottom() {
        int o = __offset(6);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float x() {
        int o = __offset(8);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float width() {
        int o = __offset(10);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public static int createFloatClip(FlatBufferBuilder builder, float yTop, float yBottom, float x, float width) {
        builder.startTable(4);
        FloatClip.addWidth(builder, width);
        FloatClip.addX(builder, x);
        FloatClip.addYBottom(builder, yBottom);
        FloatClip.addYTop(builder, yTop);
        return FloatClip.endFloatClip(builder);
    }

    public static void startFloatClip(FlatBufferBuilder builder) {
        builder.startTable(4);
    }

    public static void addYTop(FlatBufferBuilder builder, float yTop) {
        builder.addFloat(0, yTop, 0.0f);
    }

    public static void addYBottom(FlatBufferBuilder builder, float yBottom) {
        builder.addFloat(1, yBottom, 0.0f);
    }

    public static void addX(FlatBufferBuilder builder, float x) {
        builder.addFloat(2, x, 0.0f);
    }

    public static void addWidth(FlatBufferBuilder builder, float width) {
        builder.addFloat(3, width, 0.0f);
    }

    public static int endFloatClip(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public FloatClip get(int j) {
            return get(new FloatClip(), j);
        }

        public FloatClip get(FloatClip obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
