// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.Table;

@SuppressWarnings("unused")
public final class FontRequest extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static FontRequest getRootAsFontRequest(ByteBuffer _bb) {
        return getRootAsFontRequest(_bb, new FontRequest());
    }

    public static FontRequest getRootAsFontRequest(ByteBuffer _bb, FontRequest obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public FontRequest __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public long fontId() {
        int o = __offset(4);
        return o != 0 ? (long) bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L;
    }

    public float fontSize() {
        int o = __offset(6);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public long glyphIds(int j) {
        int o = __offset(8);
        return o != 0 ? (long) bb.getInt(__vector(o) + j * 4) & 0xFFFFFFFFL : 0;
    }

    public int glyphIdsLength() {
        int o = __offset(8);
        return o != 0 ? __vector_len(o) : 0;
    }

    public IntVector glyphIdsVector() {
        return glyphIdsVector(new IntVector());
    }

    public IntVector glyphIdsVector(IntVector obj) {
        int o = __offset(8);
        return o != 0 ? obj.__assign(__vector(o), bb) : null;
    }

    public ByteBuffer glyphIdsAsByteBuffer() {
        return __vector_as_bytebuffer(8, 4);
    }

    public ByteBuffer glyphIdsInByteBuffer(ByteBuffer _bb) {
        return __vector_in_bytebuffer(_bb, 8, 4);
    }

    public float posX(int j) {
        int o = __offset(10);
        return o != 0 ? bb.getFloat(__vector(o) + j * 4) : 0;
    }

    public int posXLength() {
        int o = __offset(10);
        return o != 0 ? __vector_len(o) : 0;
    }

    public FloatVector posXVector() {
        return posXVector(new FloatVector());
    }

    public FloatVector posXVector(FloatVector obj) {
        int o = __offset(10);
        return o != 0 ? obj.__assign(__vector(o), bb) : null;
    }

    public ByteBuffer posXAsByteBuffer() {
        return __vector_as_bytebuffer(10, 4);
    }

    public ByteBuffer posXInByteBuffer(ByteBuffer _bb) {
        return __vector_in_bytebuffer(_bb, 10, 4);
    }

    public float posY(int j) {
        int o = __offset(12);
        return o != 0 ? bb.getFloat(__vector(o) + j * 4) : 0;
    }

    public int posYLength() {
        int o = __offset(12);
        return o != 0 ? __vector_len(o) : 0;
    }

    public FloatVector posYVector() {
        return posYVector(new FloatVector());
    }

    public FloatVector posYVector(FloatVector obj) {
        int o = __offset(12);
        return o != 0 ? obj.__assign(__vector(o), bb) : null;
    }

    public ByteBuffer posYAsByteBuffer() {
        return __vector_as_bytebuffer(12, 4);
    }

    public ByteBuffer posYInByteBuffer(ByteBuffer _bb) {
        return __vector_in_bytebuffer(_bb, 12, 4);
    }

    public static int createFontRequest(FlatBufferBuilder builder, long fontId, float fontSize, int glyphIdsOffset,
        int posXOffset, int posYOffset) {
        builder.startTable(5);
        FontRequest.addPosY(builder, posYOffset);
        FontRequest.addPosX(builder, posXOffset);
        FontRequest.addGlyphIds(builder, glyphIdsOffset);
        FontRequest.addFontSize(builder, fontSize);
        FontRequest.addFontId(builder, fontId);
        return FontRequest.endFontRequest(builder);
    }

    public static void startFontRequest(FlatBufferBuilder builder) {
        builder.startTable(5);
    }

    public static void addFontId(FlatBufferBuilder builder, long fontId) {
        builder.addInt(0, (int) fontId, (int) 0L);
    }

    public static void addFontSize(FlatBufferBuilder builder, float fontSize) {
        builder.addFloat(1, fontSize, 0.0f);
    }

    public static void addGlyphIds(FlatBufferBuilder builder, int glyphIdsOffset) {
        builder.addOffset(2, glyphIdsOffset, 0);
    }

    public static int createGlyphIdsVector(FlatBufferBuilder builder, long[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) builder.addInt((int) data[i]);
        return builder.endVector();
    }

    public static void startGlyphIdsVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static void addPosX(FlatBufferBuilder builder, int posXOffset) {
        builder.addOffset(3, posXOffset, 0);
    }

    public static int createPosXVector(FlatBufferBuilder builder, float[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) builder.addFloat(data[i]);
        return builder.endVector();
    }

    public static void startPosXVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static void addPosY(FlatBufferBuilder builder, int posYOffset) {
        builder.addOffset(4, posYOffset, 0);
    }

    public static int createPosYVector(FlatBufferBuilder builder, float[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) builder.addFloat(data[i]);
        return builder.endVector();
    }

    public static void startPosYVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static int endFontRequest(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public FontRequest get(int j) {
            return get(new FontRequest(), j);
        }

        public FontRequest get(FontRequest obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
