// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

@SuppressWarnings("unused")
public final class GlyphPixels extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static GlyphPixels getRootAsGlyphPixels(ByteBuffer _bb) {
        return getRootAsGlyphPixels(_bb, new GlyphPixels());
    }

    public static GlyphPixels getRootAsGlyphPixels(ByteBuffer _bb, GlyphPixels obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public GlyphPixels __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public long fontId() {
        int o = __offset(4);
        return o != 0 ? (long) bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L;
    }

    public float fontSize() {
        int o = __offset(6);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public long glyphId() {
        int o = __offset(8);
        return o != 0 ? (long) bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L;
    }

    public long width() {
        int o = __offset(10);
        return o != 0 ? (long) bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L;
    }

    public long height() {
        int o = __offset(12);
        return o != 0 ? (long) bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L;
    }

    public int rgba(int j) {
        int o = __offset(14);
        return o != 0 ? bb.get(__vector(o) + j) & 0xFF : 0;
    }

    public int rgbaLength() {
        int o = __offset(14);
        return o != 0 ? __vector_len(o) : 0;
    }

    public ByteVector rgbaVector() {
        return rgbaVector(new ByteVector());
    }

    public ByteVector rgbaVector(ByteVector obj) {
        int o = __offset(14);
        return o != 0 ? obj.__assign(__vector(o), bb) : null;
    }

    public ByteBuffer rgbaAsByteBuffer() {
        return __vector_as_bytebuffer(14, 1);
    }

    public ByteBuffer rgbaInByteBuffer(ByteBuffer _bb) {
        return __vector_in_bytebuffer(_bb, 14, 1);
    }

    public static int createGlyphPixels(FlatBufferBuilder builder, long fontId, float fontSize, long glyphId,
        long width, long height, int rgbaOffset) {
        builder.startTable(6);
        GlyphPixels.addRgba(builder, rgbaOffset);
        GlyphPixels.addHeight(builder, height);
        GlyphPixels.addWidth(builder, width);
        GlyphPixels.addGlyphId(builder, glyphId);
        GlyphPixels.addFontSize(builder, fontSize);
        GlyphPixels.addFontId(builder, fontId);
        return GlyphPixels.endGlyphPixels(builder);
    }

    public static void startGlyphPixels(FlatBufferBuilder builder) {
        builder.startTable(6);
    }

    public static void addFontId(FlatBufferBuilder builder, long fontId) {
        builder.addInt(0, (int) fontId, (int) 0L);
    }

    public static void addFontSize(FlatBufferBuilder builder, float fontSize) {
        builder.addFloat(1, fontSize, 0.0f);
    }

    public static void addGlyphId(FlatBufferBuilder builder, long glyphId) {
        builder.addInt(2, (int) glyphId, (int) 0L);
    }

    public static void addWidth(FlatBufferBuilder builder, long width) {
        builder.addInt(3, (int) width, (int) 0L);
    }

    public static void addHeight(FlatBufferBuilder builder, long height) {
        builder.addInt(4, (int) height, (int) 0L);
    }

    public static void addRgba(FlatBufferBuilder builder, int rgbaOffset) {
        builder.addOffset(5, rgbaOffset, 0);
    }

    public static int createRgbaVector(FlatBufferBuilder builder, byte[] data) {
        return builder.createByteVector(data);
    }

    public static int createRgbaVector(FlatBufferBuilder builder, ByteBuffer data) {
        return builder.createByteVector(data);
    }

    public static void startRgbaVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(1, numElems, 1);
    }

    public static int endGlyphPixels(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public GlyphPixels get(int j) {
            return get(new GlyphPixels(), j);
        }

        public GlyphPixels get(GlyphPixels obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
