// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

/**
 * One glyph run of a paragraph, grouped by span: `argb` tints the (white)
 * atlas bitmaps, `shear` asks the engine for a synthetic-italic slant.
 * Default values keep legacy single-style runs white and unslanted.
 */
@SuppressWarnings("unused")
public final class GlyphRun extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static GlyphRun getRootAsGlyphRun(ByteBuffer _bb) {
        return getRootAsGlyphRun(_bb, new GlyphRun());
    }

    public static GlyphRun getRootAsGlyphRun(ByteBuffer _bb, GlyphRun obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public GlyphRun __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public long nodeIndex() {
        int o = __offset(4);
        return o != 0 ? (long) bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L;
    }

    public PlacedGlyph glyphs(int j) {
        return glyphs(new PlacedGlyph(), j);
    }

    public PlacedGlyph glyphs(PlacedGlyph obj, int j) {
        int o = __offset(6);
        return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null;
    }

    public int glyphsLength() {
        int o = __offset(6);
        return o != 0 ? __vector_len(o) : 0;
    }

    public PlacedGlyph.Vector glyphsVector() {
        return glyphsVector(new PlacedGlyph.Vector());
    }

    public PlacedGlyph.Vector glyphsVector(PlacedGlyph.Vector obj) {
        int o = __offset(6);
        return o != 0 ? obj.__assign(__vector(o), 4, bb) : null;
    }

    public long argb() {
        int o = __offset(8);
        return o != 0 ? (long) bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 4294967295L;
    }

    public boolean shear() {
        int o = __offset(10);
        return o != 0 ? 0 != bb.get(o + bb_pos) : false;
    }

    public static int createGlyphRun(FlatBufferBuilder builder, long nodeIndex, int glyphsOffset, long argb,
        boolean shear) {
        builder.startTable(4);
        GlyphRun.addArgb(builder, argb);
        GlyphRun.addGlyphs(builder, glyphsOffset);
        GlyphRun.addNodeIndex(builder, nodeIndex);
        GlyphRun.addShear(builder, shear);
        return GlyphRun.endGlyphRun(builder);
    }

    public static void startGlyphRun(FlatBufferBuilder builder) {
        builder.startTable(4);
    }

    public static void addNodeIndex(FlatBufferBuilder builder, long nodeIndex) {
        builder.addInt(0, (int) nodeIndex, (int) 0L);
    }

    public static void addGlyphs(FlatBufferBuilder builder, int glyphsOffset) {
        builder.addOffset(1, glyphsOffset, 0);
    }

    public static int createGlyphsVector(FlatBufferBuilder builder, int[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]);
        return builder.endVector();
    }

    public static void startGlyphsVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static void addArgb(FlatBufferBuilder builder, long argb) {
        builder.addInt(2, (int) argb, (int) 4294967295L);
    }

    public static void addShear(FlatBufferBuilder builder, boolean shear) {
        builder.addBoolean(3, shear, false);
    }

    public static int endGlyphRun(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public GlyphRun get(int j) {
            return get(new GlyphRun(), j);
        }

        public GlyphRun get(GlyphRun obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
