// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

@SuppressWarnings("unused")
public final class LatexDisplayData extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static LatexDisplayData getRootAsLatexDisplayData(ByteBuffer _bb) {
        return getRootAsLatexDisplayData(_bb, new LatexDisplayData());
    }

    public static LatexDisplayData getRootAsLatexDisplayData(ByteBuffer _bb, LatexDisplayData obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public LatexDisplayData __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public String formula() {
        int o = __offset(4);
        return o != 0 ? __string(o + bb_pos) : null;
    }

    public ByteBuffer formulaAsByteBuffer() {
        return __vector_as_bytebuffer(4, 1);
    }

    public ByteBuffer formulaInByteBuffer(ByteBuffer _bb) {
        return __vector_in_bytebuffer(_bb, 4, 1);
    }

    public long fillColorArgb() {
        int o = __offset(6);
        return o != 0 ? (long) bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 4294967295L;
    }

    public float sourceScale() {
        int o = __offset(8);
        return o != 0 ? bb.getFloat(o + bb_pos) : 100.0f;
    }

    public float userScale() {
        int o = __offset(10);
        return o != 0 ? bb.getFloat(o + bb_pos) : 1.0f;
    }

    public int offsetX() {
        int o = __offset(12);
        return o != 0 ? bb.getInt(o + bb_pos) : 0;
    }

    public int offsetY() {
        int o = __offset(14);
        return o != 0 ? bb.getInt(o + bb_pos) : 0;
    }

    public float rawW() {
        int o = __offset(16);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float rawH() {
        int o = __offset(18);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float refH() {
        int o = __offset(20);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public static int createLatexDisplayData(FlatBufferBuilder builder, int formulaOffset, long fillColorArgb,
        float sourceScale, float userScale, int offsetX, int offsetY, float rawW, float rawH, float refH) {
        builder.startTable(9);
        LatexDisplayData.addRefH(builder, refH);
        LatexDisplayData.addRawH(builder, rawH);
        LatexDisplayData.addRawW(builder, rawW);
        LatexDisplayData.addOffsetY(builder, offsetY);
        LatexDisplayData.addOffsetX(builder, offsetX);
        LatexDisplayData.addUserScale(builder, userScale);
        LatexDisplayData.addSourceScale(builder, sourceScale);
        LatexDisplayData.addFillColorArgb(builder, fillColorArgb);
        LatexDisplayData.addFormula(builder, formulaOffset);
        return LatexDisplayData.endLatexDisplayData(builder);
    }

    public static void startLatexDisplayData(FlatBufferBuilder builder) {
        builder.startTable(9);
    }

    public static void addFormula(FlatBufferBuilder builder, int formulaOffset) {
        builder.addOffset(0, formulaOffset, 0);
    }

    public static void addFillColorArgb(FlatBufferBuilder builder, long fillColorArgb) {
        builder.addInt(1, (int) fillColorArgb, (int) 4294967295L);
    }

    public static void addSourceScale(FlatBufferBuilder builder, float sourceScale) {
        builder.addFloat(2, sourceScale, 100.0f);
    }

    public static void addUserScale(FlatBufferBuilder builder, float userScale) {
        builder.addFloat(3, userScale, 1.0f);
    }

    public static void addOffsetX(FlatBufferBuilder builder, int offsetX) {
        builder.addInt(4, offsetX, 0);
    }

    public static void addOffsetY(FlatBufferBuilder builder, int offsetY) {
        builder.addInt(5, offsetY, 0);
    }

    public static void addRawW(FlatBufferBuilder builder, float rawW) {
        builder.addFloat(6, rawW, 0.0f);
    }

    public static void addRawH(FlatBufferBuilder builder, float rawH) {
        builder.addFloat(7, rawH, 0.0f);
    }

    public static void addRefH(FlatBufferBuilder builder, float refH) {
        builder.addFloat(8, refH, 0.0f);
    }

    public static int endLatexDisplayData(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public LatexDisplayData get(int j) {
            return get(new LatexDisplayData(), j);
        }

        public LatexDisplayData get(LatexDisplayData obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
