// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

@SuppressWarnings("unused")
public final class LayoutResult extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static LayoutResult getRootAsLayoutResult(ByteBuffer _bb) {
        return getRootAsLayoutResult(_bb, new LayoutResult());
    }

    public static LayoutResult getRootAsLayoutResult(ByteBuffer _bb, LayoutResult obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public LayoutResult __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public FlatLayout nodes(int j) {
        return nodes(new FlatLayout(), j);
    }

    public FlatLayout nodes(FlatLayout obj, int j) {
        int o = __offset(4);
        return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null;
    }

    public int nodesLength() {
        int o = __offset(4);
        return o != 0 ? __vector_len(o) : 0;
    }

    public FlatLayout.Vector nodesVector() {
        return nodesVector(new FlatLayout.Vector());
    }

    public FlatLayout.Vector nodesVector(FlatLayout.Vector obj) {
        int o = __offset(4);
        return o != 0 ? obj.__assign(__vector(o), 4, bb) : null;
    }

    public GlyphRun glyphRuns(int j) {
        return glyphRuns(new GlyphRun(), j);
    }

    public GlyphRun glyphRuns(GlyphRun obj, int j) {
        int o = __offset(6);
        return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null;
    }

    public int glyphRunsLength() {
        int o = __offset(6);
        return o != 0 ? __vector_len(o) : 0;
    }

    public GlyphRun.Vector glyphRunsVector() {
        return glyphRunsVector(new GlyphRun.Vector());
    }

    public GlyphRun.Vector glyphRunsVector(GlyphRun.Vector obj) {
        int o = __offset(6);
        return o != 0 ? obj.__assign(__vector(o), 4, bb) : null;
    }

    public GlyphBitmap bitmaps(int j) {
        return bitmaps(new GlyphBitmap(), j);
    }

    public GlyphBitmap bitmaps(GlyphBitmap obj, int j) {
        int o = __offset(8);
        return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null;
    }

    public int bitmapsLength() {
        int o = __offset(8);
        return o != 0 ? __vector_len(o) : 0;
    }

    public GlyphBitmap.Vector bitmapsVector() {
        return bitmapsVector(new GlyphBitmap.Vector());
    }

    public GlyphBitmap.Vector bitmapsVector(GlyphBitmap.Vector obj) {
        int o = __offset(8);
        return o != 0 ? obj.__assign(__vector(o), 4, bb) : null;
    }

    public DecorationRect decorations(int j) {
        return decorations(new DecorationRect(), j);
    }

    public DecorationRect decorations(DecorationRect obj, int j) {
        int o = __offset(10);
        return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null;
    }

    public int decorationsLength() {
        int o = __offset(10);
        return o != 0 ? __vector_len(o) : 0;
    }

    public DecorationRect.Vector decorationsVector() {
        return decorationsVector(new DecorationRect.Vector());
    }

    public DecorationRect.Vector decorationsVector(DecorationRect.Vector obj) {
        int o = __offset(10);
        return o != 0 ? obj.__assign(__vector(o), 4, bb) : null;
    }

    public float contentHeight() {
        int o = __offset(12);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public String debugInfo() {
        int o = __offset(14);
        return o != 0 ? __string(o + bb_pos) : null;
    }

    public ByteBuffer debugInfoAsByteBuffer() {
        return __vector_as_bytebuffer(14, 1);
    }

    public ByteBuffer debugInfoInByteBuffer(ByteBuffer _bb) {
        return __vector_in_bytebuffer(_bb, 14, 1);
    }

    public static int createLayoutResult(FlatBufferBuilder builder, int nodesOffset, int glyphRunsOffset,
        int bitmapsOffset, int decorationsOffset, float contentHeight, int debugInfoOffset) {
        builder.startTable(6);
        LayoutResult.addDebugInfo(builder, debugInfoOffset);
        LayoutResult.addContentHeight(builder, contentHeight);
        LayoutResult.addDecorations(builder, decorationsOffset);
        LayoutResult.addBitmaps(builder, bitmapsOffset);
        LayoutResult.addGlyphRuns(builder, glyphRunsOffset);
        LayoutResult.addNodes(builder, nodesOffset);
        return LayoutResult.endLayoutResult(builder);
    }

    public static void startLayoutResult(FlatBufferBuilder builder) {
        builder.startTable(6);
    }

    public static void addNodes(FlatBufferBuilder builder, int nodesOffset) {
        builder.addOffset(0, nodesOffset, 0);
    }

    public static int createNodesVector(FlatBufferBuilder builder, int[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]);
        return builder.endVector();
    }

    public static void startNodesVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static void addGlyphRuns(FlatBufferBuilder builder, int glyphRunsOffset) {
        builder.addOffset(1, glyphRunsOffset, 0);
    }

    public static int createGlyphRunsVector(FlatBufferBuilder builder, int[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]);
        return builder.endVector();
    }

    public static void startGlyphRunsVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static void addBitmaps(FlatBufferBuilder builder, int bitmapsOffset) {
        builder.addOffset(2, bitmapsOffset, 0);
    }

    public static int createBitmapsVector(FlatBufferBuilder builder, int[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]);
        return builder.endVector();
    }

    public static void startBitmapsVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static void addDecorations(FlatBufferBuilder builder, int decorationsOffset) {
        builder.addOffset(3, decorationsOffset, 0);
    }

    public static int createDecorationsVector(FlatBufferBuilder builder, int[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]);
        return builder.endVector();
    }

    public static void startDecorationsVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static void addContentHeight(FlatBufferBuilder builder, float contentHeight) {
        builder.addFloat(4, contentHeight, 0.0f);
    }

    public static void addDebugInfo(FlatBufferBuilder builder, int debugInfoOffset) {
        builder.addOffset(5, debugInfoOffset, 0);
    }

    public static int endLayoutResult(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public LayoutResult get(int j) {
            return get(new LayoutResult(), j);
        }

        public LayoutResult get(LayoutResult obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
