// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

@SuppressWarnings("unused")
public final class RasterResult extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static RasterResult getRootAsRasterResult(ByteBuffer _bb) {
        return getRootAsRasterResult(_bb, new RasterResult());
    }

    public static RasterResult getRootAsRasterResult(ByteBuffer _bb, RasterResult obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public RasterResult __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public GlyphPixels glyphs(int j) {
        return glyphs(new GlyphPixels(), j);
    }

    public GlyphPixels glyphs(GlyphPixels obj, int j) {
        int o = __offset(4);
        return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null;
    }

    public int glyphsLength() {
        int o = __offset(4);
        return o != 0 ? __vector_len(o) : 0;
    }

    public GlyphPixels.Vector glyphsVector() {
        return glyphsVector(new GlyphPixels.Vector());
    }

    public GlyphPixels.Vector glyphsVector(GlyphPixels.Vector obj) {
        int o = __offset(4);
        return o != 0 ? obj.__assign(__vector(o), 4, bb) : null;
    }

    public static int createRasterResult(FlatBufferBuilder builder, int glyphsOffset) {
        builder.startTable(1);
        RasterResult.addGlyphs(builder, glyphsOffset);
        return RasterResult.endRasterResult(builder);
    }

    public static void startRasterResult(FlatBufferBuilder builder) {
        builder.startTable(1);
    }

    public static void addGlyphs(FlatBufferBuilder builder, int glyphsOffset) {
        builder.addOffset(0, glyphsOffset, 0);
    }

    public static int createGlyphsVector(FlatBufferBuilder builder, int[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]);
        return builder.endVector();
    }

    public static void startGlyphsVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static int endRasterResult(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public RasterResult get(int j) {
            return get(new RasterResult(), j);
        }

        public RasterResult get(RasterResult obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
