// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

@SuppressWarnings("unused")
public final class ShapeTextResult extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static ShapeTextResult getRootAsShapeTextResult(ByteBuffer _bb) {
        return getRootAsShapeTextResult(_bb, new ShapeTextResult());
    }

    public static ShapeTextResult getRootAsShapeTextResult(ByteBuffer _bb, ShapeTextResult obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public ShapeTextResult __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public float width() {
        int o = __offset(4);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float height() {
        int o = __offset(6);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float ascent() {
        int o = __offset(8);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float lineHeight() {
        int o = __offset(10);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public PlacedGlyph glyphs(int j) {
        return glyphs(new PlacedGlyph(), j);
    }

    public PlacedGlyph glyphs(PlacedGlyph obj, int j) {
        int o = __offset(12);
        return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null;
    }

    public int glyphsLength() {
        int o = __offset(12);
        return o != 0 ? __vector_len(o) : 0;
    }

    public PlacedGlyph.Vector glyphsVector() {
        return glyphsVector(new PlacedGlyph.Vector());
    }

    public PlacedGlyph.Vector glyphsVector(PlacedGlyph.Vector obj) {
        int o = __offset(12);
        return o != 0 ? obj.__assign(__vector(o), 4, bb) : null;
    }

    public GlyphBitmap bitmaps(int j) {
        return bitmaps(new GlyphBitmap(), j);
    }

    public GlyphBitmap bitmaps(GlyphBitmap obj, int j) {
        int o = __offset(14);
        return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null;
    }

    public int bitmapsLength() {
        int o = __offset(14);
        return o != 0 ? __vector_len(o) : 0;
    }

    public GlyphBitmap.Vector bitmapsVector() {
        return bitmapsVector(new GlyphBitmap.Vector());
    }

    public GlyphBitmap.Vector bitmapsVector(GlyphBitmap.Vector obj) {
        int o = __offset(14);
        return o != 0 ? obj.__assign(__vector(o), 4, bb) : null;
    }

    public float xHeight() {
        int o = __offset(16);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float capHeight() {
        int o = __offset(18);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public static int createShapeTextResult(FlatBufferBuilder builder, float width, float height, float ascent,
        float lineHeight, int glyphsOffset, int bitmapsOffset, float xHeight, float capHeight) {
        builder.startTable(8);
        ShapeTextResult.addCapHeight(builder, capHeight);
        ShapeTextResult.addXHeight(builder, xHeight);
        ShapeTextResult.addBitmaps(builder, bitmapsOffset);
        ShapeTextResult.addGlyphs(builder, glyphsOffset);
        ShapeTextResult.addLineHeight(builder, lineHeight);
        ShapeTextResult.addAscent(builder, ascent);
        ShapeTextResult.addHeight(builder, height);
        ShapeTextResult.addWidth(builder, width);
        return ShapeTextResult.endShapeTextResult(builder);
    }

    public static void startShapeTextResult(FlatBufferBuilder builder) {
        builder.startTable(8);
    }

    public static void addWidth(FlatBufferBuilder builder, float width) {
        builder.addFloat(0, width, 0.0f);
    }

    public static void addHeight(FlatBufferBuilder builder, float height) {
        builder.addFloat(1, height, 0.0f);
    }

    public static void addAscent(FlatBufferBuilder builder, float ascent) {
        builder.addFloat(2, ascent, 0.0f);
    }

    public static void addLineHeight(FlatBufferBuilder builder, float lineHeight) {
        builder.addFloat(3, lineHeight, 0.0f);
    }

    public static void addGlyphs(FlatBufferBuilder builder, int glyphsOffset) {
        builder.addOffset(4, glyphsOffset, 0);
    }

    public static int createGlyphsVector(FlatBufferBuilder builder, int[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]);
        return builder.endVector();
    }

    public static void startGlyphsVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static void addBitmaps(FlatBufferBuilder builder, int bitmapsOffset) {
        builder.addOffset(5, bitmapsOffset, 0);
    }

    public static int createBitmapsVector(FlatBufferBuilder builder, int[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]);
        return builder.endVector();
    }

    public static void startBitmapsVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static void addXHeight(FlatBufferBuilder builder, float xHeight) {
        builder.addFloat(6, xHeight, 0.0f);
    }

    public static void addCapHeight(FlatBufferBuilder builder, float capHeight) {
        builder.addFloat(7, capHeight, 0.0f);
    }

    public static int endShapeTextResult(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public ShapeTextResult get(int j) {
            return get(new ShapeTextResult(), j);
        }

        public ShapeTextResult get(ShapeTextResult obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
