// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

/**
 * Isometric structure view sizing data (node_type 26).
 * Mirrors LytStructureView.computeLayout: view_width/view_height are the
 * block's intrinsic dimensions (setViewSize or DEFAULT_WIDTH/HEIGHT), used
 * by the Rust measure function with visual_scale and available_width to
 * compute the responsive box.
 */
@SuppressWarnings("unused")
public final class StructureViewData extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static StructureViewData getRootAsStructureViewData(ByteBuffer _bb) {
        return getRootAsStructureViewData(_bb, new StructureViewData());
    }

    public static StructureViewData getRootAsStructureViewData(ByteBuffer _bb, StructureViewData obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public StructureViewData __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public float viewWidth() {
        int o = __offset(4);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float viewHeight() {
        int o = __offset(6);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public static int createStructureViewData(FlatBufferBuilder builder, float viewWidth, float viewHeight) {
        builder.startTable(2);
        StructureViewData.addViewHeight(builder, viewHeight);
        StructureViewData.addViewWidth(builder, viewWidth);
        return StructureViewData.endStructureViewData(builder);
    }

    public static void startStructureViewData(FlatBufferBuilder builder) {
        builder.startTable(2);
    }

    public static void addViewWidth(FlatBufferBuilder builder, float viewWidth) {
        builder.addFloat(0, viewWidth, 0.0f);
    }

    public static void addViewHeight(FlatBufferBuilder builder, float viewHeight) {
        builder.addFloat(1, viewHeight, 0.0f);
    }

    public static int endStructureViewData(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public StructureViewData get(int j) {
            return get(new StructureViewData(), j);
        }

        public StructureViewData get(StructureViewData obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
