// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

@SuppressWarnings("unused")
public final class Style extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static Style getRootAsStyle(ByteBuffer _bb) {
        return getRootAsStyle(_bb, new Style());
    }

    public static Style getRootAsStyle(ByteBuffer _bb, Style obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public Style __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public byte display() {
        int o = __offset(4);
        return o != 0 ? bb.get(o + bb_pos) : 0;
    }

    public byte flexDirection() {
        int o = __offset(6);
        return o != 0 ? bb.get(o + bb_pos) : 1;
    }

    public byte flexWrap() {
        int o = __offset(8);
        return o != 0 ? bb.get(o + bb_pos) : 0;
    }

    public byte alignItems() {
        int o = __offset(10);
        return o != 0 ? bb.get(o + bb_pos) : 0;
    }

    public byte alignSelf() {
        int o = __offset(12);
        return o != 0 ? bb.get(o + bb_pos) : 0;
    }

    public byte justifyContent() {
        int o = __offset(14);
        return o != 0 ? bb.get(o + bb_pos) : 0;
    }

    public Dimension gapW() {
        return gapW(new Dimension());
    }

    public Dimension gapW(Dimension obj) {
        int o = __offset(16);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public Dimension gapH() {
        return gapH(new Dimension());
    }

    public Dimension gapH(Dimension obj) {
        int o = __offset(18);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public Dimension sizeW() {
        return sizeW(new Dimension());
    }

    public Dimension sizeW(Dimension obj) {
        int o = __offset(20);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public Dimension sizeH() {
        return sizeH(new Dimension());
    }

    public Dimension sizeH(Dimension obj) {
        int o = __offset(22);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public Dimension minW() {
        return minW(new Dimension());
    }

    public Dimension minW(Dimension obj) {
        int o = __offset(24);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public Dimension minH() {
        return minH(new Dimension());
    }

    public Dimension minH(Dimension obj) {
        int o = __offset(26);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public Dimension maxW() {
        return maxW(new Dimension());
    }

    public Dimension maxW(Dimension obj) {
        int o = __offset(28);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public Dimension maxH() {
        return maxH(new Dimension());
    }

    public Dimension maxH(Dimension obj) {
        int o = __offset(30);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public float aspectRatio() {
        int o = __offset(32);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float marginLeft() {
        int o = __offset(34);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float marginRight() {
        int o = __offset(36);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float marginTop() {
        int o = __offset(38);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float marginBottom() {
        int o = __offset(40);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public boolean marginAutoLeft() {
        int o = __offset(42);
        return o != 0 ? 0 != bb.get(o + bb_pos) : false;
    }

    public boolean marginAutoRight() {
        int o = __offset(44);
        return o != 0 ? 0 != bb.get(o + bb_pos) : false;
    }

    public boolean marginAutoTop() {
        int o = __offset(46);
        return o != 0 ? 0 != bb.get(o + bb_pos) : false;
    }

    public boolean marginAutoBottom() {
        int o = __offset(48);
        return o != 0 ? 0 != bb.get(o + bb_pos) : false;
    }

    public float paddingLeft() {
        int o = __offset(50);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float paddingRight() {
        int o = __offset(52);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float paddingTop() {
        int o = __offset(54);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float paddingBottom() {
        int o = __offset(56);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float borderLeft() {
        int o = __offset(58);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float borderRight() {
        int o = __offset(60);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float borderTop() {
        int o = __offset(62);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float borderBottom() {
        int o = __offset(64);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public byte overflow() {
        int o = __offset(66);
        return o != 0 ? bb.get(o + bb_pos) : 0;
    }

    public float flexGrow() {
        int o = __offset(68);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public float flexShrink() {
        int o = __offset(70);
        return o != 0 ? bb.getFloat(o + bb_pos) : 1.0f;
    }

    public Dimension flexBasis() {
        return flexBasis(new Dimension());
    }

    public Dimension flexBasis(Dimension obj) {
        int o = __offset(72);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public byte float_() {
        int o = __offset(74);
        return o != 0 ? bb.get(o + bb_pos) : 0;
    }

    public byte clear() {
        int o = __offset(76);
        return o != 0 ? bb.get(o + bb_pos) : 0;
    }

    public byte position() {
        int o = __offset(78);
        return o != 0 ? bb.get(o + bb_pos) : 0;
    }

    public Dimension insetTop() {
        return insetTop(new Dimension());
    }

    public Dimension insetTop(Dimension obj) {
        int o = __offset(80);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public Dimension insetRight() {
        return insetRight(new Dimension());
    }

    public Dimension insetRight(Dimension obj) {
        int o = __offset(82);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public Dimension insetBottom() {
        return insetBottom(new Dimension());
    }

    public Dimension insetBottom(Dimension obj) {
        int o = __offset(84);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public Dimension insetLeft() {
        return insetLeft(new Dimension());
    }

    public Dimension insetLeft(Dimension obj) {
        int o = __offset(86);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public static int createStyle(FlatBufferBuilder builder, byte display, byte flexDirection, byte flexWrap,
        byte alignItems, byte alignSelf, byte justifyContent, int gapWOffset, int gapHOffset, int sizeWOffset,
        int sizeHOffset, int minWOffset, int minHOffset, int maxWOffset, int maxHOffset, float aspectRatio,
        float marginLeft, float marginRight, float marginTop, float marginBottom, boolean marginAutoLeft,
        boolean marginAutoRight, boolean marginAutoTop, boolean marginAutoBottom, float paddingLeft, float paddingRight,
        float paddingTop, float paddingBottom, float borderLeft, float borderRight, float borderTop, float borderBottom,
        byte overflow, float flexGrow, float flexShrink, int flexBasisOffset, byte float_, byte clear, byte position,
        int insetTopOffset, int insetRightOffset, int insetBottomOffset, int insetLeftOffset) {
        builder.startTable(42);
        Style.addInsetLeft(builder, insetLeftOffset);
        Style.addInsetBottom(builder, insetBottomOffset);
        Style.addInsetRight(builder, insetRightOffset);
        Style.addInsetTop(builder, insetTopOffset);
        Style.addFlexBasis(builder, flexBasisOffset);
        Style.addFlexShrink(builder, flexShrink);
        Style.addFlexGrow(builder, flexGrow);
        Style.addBorderBottom(builder, borderBottom);
        Style.addBorderTop(builder, borderTop);
        Style.addBorderRight(builder, borderRight);
        Style.addBorderLeft(builder, borderLeft);
        Style.addPaddingBottom(builder, paddingBottom);
        Style.addPaddingTop(builder, paddingTop);
        Style.addPaddingRight(builder, paddingRight);
        Style.addPaddingLeft(builder, paddingLeft);
        Style.addMarginBottom(builder, marginBottom);
        Style.addMarginTop(builder, marginTop);
        Style.addMarginRight(builder, marginRight);
        Style.addMarginLeft(builder, marginLeft);
        Style.addAspectRatio(builder, aspectRatio);
        Style.addMaxH(builder, maxHOffset);
        Style.addMaxW(builder, maxWOffset);
        Style.addMinH(builder, minHOffset);
        Style.addMinW(builder, minWOffset);
        Style.addSizeH(builder, sizeHOffset);
        Style.addSizeW(builder, sizeWOffset);
        Style.addGapH(builder, gapHOffset);
        Style.addGapW(builder, gapWOffset);
        Style.addPosition(builder, position);
        Style.addClear(builder, clear);
        Style.addFloat(builder, float_);
        Style.addOverflow(builder, overflow);
        Style.addMarginAutoBottom(builder, marginAutoBottom);
        Style.addMarginAutoTop(builder, marginAutoTop);
        Style.addMarginAutoRight(builder, marginAutoRight);
        Style.addMarginAutoLeft(builder, marginAutoLeft);
        Style.addJustifyContent(builder, justifyContent);
        Style.addAlignSelf(builder, alignSelf);
        Style.addAlignItems(builder, alignItems);
        Style.addFlexWrap(builder, flexWrap);
        Style.addFlexDirection(builder, flexDirection);
        Style.addDisplay(builder, display);
        return Style.endStyle(builder);
    }

    public static void startStyle(FlatBufferBuilder builder) {
        builder.startTable(42);
    }

    public static void addDisplay(FlatBufferBuilder builder, byte display) {
        builder.addByte(0, display, 0);
    }

    public static void addFlexDirection(FlatBufferBuilder builder, byte flexDirection) {
        builder.addByte(1, flexDirection, 1);
    }

    public static void addFlexWrap(FlatBufferBuilder builder, byte flexWrap) {
        builder.addByte(2, flexWrap, 0);
    }

    public static void addAlignItems(FlatBufferBuilder builder, byte alignItems) {
        builder.addByte(3, alignItems, 0);
    }

    public static void addAlignSelf(FlatBufferBuilder builder, byte alignSelf) {
        builder.addByte(4, alignSelf, 0);
    }

    public static void addJustifyContent(FlatBufferBuilder builder, byte justifyContent) {
        builder.addByte(5, justifyContent, 0);
    }

    public static void addGapW(FlatBufferBuilder builder, int gapWOffset) {
        builder.addOffset(6, gapWOffset, 0);
    }

    public static void addGapH(FlatBufferBuilder builder, int gapHOffset) {
        builder.addOffset(7, gapHOffset, 0);
    }

    public static void addSizeW(FlatBufferBuilder builder, int sizeWOffset) {
        builder.addOffset(8, sizeWOffset, 0);
    }

    public static void addSizeH(FlatBufferBuilder builder, int sizeHOffset) {
        builder.addOffset(9, sizeHOffset, 0);
    }

    public static void addMinW(FlatBufferBuilder builder, int minWOffset) {
        builder.addOffset(10, minWOffset, 0);
    }

    public static void addMinH(FlatBufferBuilder builder, int minHOffset) {
        builder.addOffset(11, minHOffset, 0);
    }

    public static void addMaxW(FlatBufferBuilder builder, int maxWOffset) {
        builder.addOffset(12, maxWOffset, 0);
    }

    public static void addMaxH(FlatBufferBuilder builder, int maxHOffset) {
        builder.addOffset(13, maxHOffset, 0);
    }

    public static void addAspectRatio(FlatBufferBuilder builder, float aspectRatio) {
        builder.addFloat(14, aspectRatio, 0.0f);
    }

    public static void addMarginLeft(FlatBufferBuilder builder, float marginLeft) {
        builder.addFloat(15, marginLeft, 0.0f);
    }

    public static void addMarginRight(FlatBufferBuilder builder, float marginRight) {
        builder.addFloat(16, marginRight, 0.0f);
    }

    public static void addMarginTop(FlatBufferBuilder builder, float marginTop) {
        builder.addFloat(17, marginTop, 0.0f);
    }

    public static void addMarginBottom(FlatBufferBuilder builder, float marginBottom) {
        builder.addFloat(18, marginBottom, 0.0f);
    }

    public static void addMarginAutoLeft(FlatBufferBuilder builder, boolean marginAutoLeft) {
        builder.addBoolean(19, marginAutoLeft, false);
    }

    public static void addMarginAutoRight(FlatBufferBuilder builder, boolean marginAutoRight) {
        builder.addBoolean(20, marginAutoRight, false);
    }

    public static void addMarginAutoTop(FlatBufferBuilder builder, boolean marginAutoTop) {
        builder.addBoolean(21, marginAutoTop, false);
    }

    public static void addMarginAutoBottom(FlatBufferBuilder builder, boolean marginAutoBottom) {
        builder.addBoolean(22, marginAutoBottom, false);
    }

    public static void addPaddingLeft(FlatBufferBuilder builder, float paddingLeft) {
        builder.addFloat(23, paddingLeft, 0.0f);
    }

    public static void addPaddingRight(FlatBufferBuilder builder, float paddingRight) {
        builder.addFloat(24, paddingRight, 0.0f);
    }

    public static void addPaddingTop(FlatBufferBuilder builder, float paddingTop) {
        builder.addFloat(25, paddingTop, 0.0f);
    }

    public static void addPaddingBottom(FlatBufferBuilder builder, float paddingBottom) {
        builder.addFloat(26, paddingBottom, 0.0f);
    }

    public static void addBorderLeft(FlatBufferBuilder builder, float borderLeft) {
        builder.addFloat(27, borderLeft, 0.0f);
    }

    public static void addBorderRight(FlatBufferBuilder builder, float borderRight) {
        builder.addFloat(28, borderRight, 0.0f);
    }

    public static void addBorderTop(FlatBufferBuilder builder, float borderTop) {
        builder.addFloat(29, borderTop, 0.0f);
    }

    public static void addBorderBottom(FlatBufferBuilder builder, float borderBottom) {
        builder.addFloat(30, borderBottom, 0.0f);
    }

    public static void addOverflow(FlatBufferBuilder builder, byte overflow) {
        builder.addByte(31, overflow, 0);
    }

    public static void addFlexGrow(FlatBufferBuilder builder, float flexGrow) {
        builder.addFloat(32, flexGrow, 0.0f);
    }

    public static void addFlexShrink(FlatBufferBuilder builder, float flexShrink) {
        builder.addFloat(33, flexShrink, 1.0f);
    }

    public static void addFlexBasis(FlatBufferBuilder builder, int flexBasisOffset) {
        builder.addOffset(34, flexBasisOffset, 0);
    }

    public static void addFloat(FlatBufferBuilder builder, byte float_) {
        builder.addByte(35, float_, 0);
    }

    public static void addClear(FlatBufferBuilder builder, byte clear) {
        builder.addByte(36, clear, 0);
    }

    public static void addPosition(FlatBufferBuilder builder, byte position) {
        builder.addByte(37, position, 0);
    }

    public static void addInsetTop(FlatBufferBuilder builder, int insetTopOffset) {
        builder.addOffset(38, insetTopOffset, 0);
    }

    public static void addInsetRight(FlatBufferBuilder builder, int insetRightOffset) {
        builder.addOffset(39, insetRightOffset, 0);
    }

    public static void addInsetBottom(FlatBufferBuilder builder, int insetBottomOffset) {
        builder.addOffset(40, insetBottomOffset, 0);
    }

    public static void addInsetLeft(FlatBufferBuilder builder, int insetLeftOffset) {
        builder.addOffset(41, insetLeftOffset, 0);
    }

    public static int endStyle(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public Style get(int j) {
            return get(new Style(), j);
        }

        public Style get(Style obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
