// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

@SuppressWarnings("unused")
public final class TextStyle extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static TextStyle getRootAsTextStyle(ByteBuffer _bb) {
        return getRootAsTextStyle(_bb, new TextStyle());
    }

    public static TextStyle getRootAsTextStyle(ByteBuffer _bb, TextStyle obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public TextStyle __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public float fontSize() {
        int o = __offset(4);
        return o != 0 ? bb.getFloat(o + bb_pos) : 14.0f;
    }

    public boolean bold() {
        int o = __offset(6);
        return o != 0 ? 0 != bb.get(o + bb_pos) : false;
    }

    public boolean italic() {
        int o = __offset(8);
        return o != 0 ? 0 != bb.get(o + bb_pos) : false;
    }

    public float fontScale() {
        int o = __offset(10);
        return o != 0 ? bb.getFloat(o + bb_pos) : 1.0f;
    }

    public long color() {
        int o = __offset(12);
        return o != 0 ? (long) bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 4294967295L;
    }

    public long font() {
        int o = __offset(14);
        return o != 0 ? (long) bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L;
    }

    public boolean underline() {
        int o = __offset(16);
        return o != 0 ? 0 != bb.get(o + bb_pos) : false;
    }

    public boolean strikethrough() {
        int o = __offset(18);
        return o != 0 ? 0 != bb.get(o + bb_pos) : false;
    }

    public long highlightArgb() {
        int o = __offset(20);
        return o != 0 ? (long) bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L;
    }

    public boolean inlineCode() {
        int o = __offset(22);
        return o != 0 ? 0 != bb.get(o + bb_pos) : false;
    }

    public float baselineShift() {
        int o = __offset(24);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }

    public boolean wavyUnderline() {
        int o = __offset(26);
        return o != 0 ? 0 != bb.get(o + bb_pos) : false;
    }

    public boolean dottedUnderline() {
        int o = __offset(28);
        return o != 0 ? 0 != bb.get(o + bb_pos) : false;
    }

    public static int createTextStyle(FlatBufferBuilder builder, float fontSize, boolean bold, boolean italic,
        float fontScale, long color, long font, boolean underline, boolean strikethrough, long highlightArgb,
        boolean inlineCode, float baselineShift, boolean wavyUnderline, boolean dottedUnderline) {
        builder.startTable(13);
        TextStyle.addBaselineShift(builder, baselineShift);
        TextStyle.addHighlightArgb(builder, highlightArgb);
        TextStyle.addFont(builder, font);
        TextStyle.addColor(builder, color);
        TextStyle.addFontScale(builder, fontScale);
        TextStyle.addFontSize(builder, fontSize);
        TextStyle.addDottedUnderline(builder, dottedUnderline);
        TextStyle.addWavyUnderline(builder, wavyUnderline);
        TextStyle.addInlineCode(builder, inlineCode);
        TextStyle.addStrikethrough(builder, strikethrough);
        TextStyle.addUnderline(builder, underline);
        TextStyle.addItalic(builder, italic);
        TextStyle.addBold(builder, bold);
        return TextStyle.endTextStyle(builder);
    }

    public static void startTextStyle(FlatBufferBuilder builder) {
        builder.startTable(13);
    }

    public static void addFontSize(FlatBufferBuilder builder, float fontSize) {
        builder.addFloat(0, fontSize, 14.0f);
    }

    public static void addBold(FlatBufferBuilder builder, boolean bold) {
        builder.addBoolean(1, bold, false);
    }

    public static void addItalic(FlatBufferBuilder builder, boolean italic) {
        builder.addBoolean(2, italic, false);
    }

    public static void addFontScale(FlatBufferBuilder builder, float fontScale) {
        builder.addFloat(3, fontScale, 1.0f);
    }

    public static void addColor(FlatBufferBuilder builder, long color) {
        builder.addInt(4, (int) color, (int) 4294967295L);
    }

    public static void addFont(FlatBufferBuilder builder, long font) {
        builder.addInt(5, (int) font, (int) 0L);
    }

    public static void addUnderline(FlatBufferBuilder builder, boolean underline) {
        builder.addBoolean(6, underline, false);
    }

    public static void addStrikethrough(FlatBufferBuilder builder, boolean strikethrough) {
        builder.addBoolean(7, strikethrough, false);
    }

    public static void addHighlightArgb(FlatBufferBuilder builder, long highlightArgb) {
        builder.addInt(8, (int) highlightArgb, (int) 0L);
    }

    public static void addInlineCode(FlatBufferBuilder builder, boolean inlineCode) {
        builder.addBoolean(9, inlineCode, false);
    }

    public static void addBaselineShift(FlatBufferBuilder builder, float baselineShift) {
        builder.addFloat(10, baselineShift, 0.0f);
    }

    public static void addWavyUnderline(FlatBufferBuilder builder, boolean wavyUnderline) {
        builder.addBoolean(11, wavyUnderline, false);
    }

    public static void addDottedUnderline(FlatBufferBuilder builder, boolean dottedUnderline) {
        builder.addBoolean(12, dottedUnderline, false);
    }

    public static int endTextStyle(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public TextStyle get(int j) {
            return get(new TextStyle(), j);
        }

        public TextStyle get(TextStyle obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
