// automatically generated by the FlatBuffers compiler, do not modify

package com.hfstudio.guidenh.guide.layout.flatbuffers;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

@SuppressWarnings("unused")
public final class ThematicBreakData extends Table {

    public static void ValidateVersion() {
        Constants.FLATBUFFERS_23_5_26();
    }

    public static ThematicBreakData getRootAsThematicBreakData(ByteBuffer _bb) {
        return getRootAsThematicBreakData(_bb, new ThematicBreakData());
    }

    public static ThematicBreakData getRootAsThematicBreakData(ByteBuffer _bb, ThematicBreakData obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public ThematicBreakData __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public float height() {
        int o = __offset(4);
        return o != 0 ? bb.getFloat(o + bb_pos) : 6.0f;
    }

    public static int createThematicBreakData(FlatBufferBuilder builder, float height) {
        builder.startTable(1);
        ThematicBreakData.addHeight(builder, height);
        return ThematicBreakData.endThematicBreakData(builder);
    }

    public static void startThematicBreakData(FlatBufferBuilder builder) {
        builder.startTable(1);
    }

    public static void addHeight(FlatBufferBuilder builder, float height) {
        builder.addFloat(0, height, 6.0f);
    }

    public static int endThematicBreakData(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {

        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public ThematicBreakData get(int j) {
            return get(new ThematicBreakData(), j);
        }

        public ThematicBreakData get(ThematicBreakData obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}
